version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    ports:
      - "9000:9000"
      - "8812:8812"
   
  cassandra:
    image: cassandra:latest
    container_name: my-cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra
    networks:
      - cassandra-network
  
networks:
  cassandra-network:
    driver: bridge
    
volumes:
  mongodb_data:

